require("core.options")
-- require("core.statusline")
require("core.keymaps")
require("core.autocmds")
require("core.commands")
require("core.transparency")

require("plugins.pack")
require("plugins.theme")
require("plugins.whichkey")
require("plugins.treesitter")
require("plugins.fzf")
require("plugins.mini")
require("plugins.lsp")
require("plugins.debug")
require("plugins.gitsigns")
require("plugins.snacks")
require("plugins.noice")
require("plugins.oil")
require("plugins.conform")
